on:
  push:
    branches:
      - master

env:
  DEV_APP_RESOURCE_GROUP_NAME: "development-ocr"
  DEV_STORAGE_ACCOUNT_NAME: "devocrstorageaccount"
  DEV_CONTAINER_NAME: "devocrstoragecontainer"

jobs:  
  get-key:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli
    outputs:
      output-access-key: ${{steps.id.outputs.access-key}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get-key
        id: id
        run: |
          az login --service-principal --username ${{secrets.DEV_ARM_CLIENT_ID}} --password ${{secrets.DEV_ARM_CLIENT_SECRET}} --tenant ${{secrets.DEV_ARM_TENANT_ID}}
          az account set --subscription ${{secrets.DEV_ARM_SUBSCRIPTION_ID}}
          ACCESS_KEY=$(az storage account keys list --resource-group $DEV_APP_RESOURCE_GROUP_NAME --account-name $DEV_STORAGE_ACCOUNT_NAME --query '[0].value' -o tsv)
          echo "access-key=$ACCESS_KEY" >> $GITHUB_OUTPUT

  deploy:
    env:
      ARM_CLIENT_ID: ${{secrets.DEV_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.DEV_ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{secrets.DEV_ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.DEV_ARM_SUBSCRIPTION_ID}}
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    needs: get-key
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: |
          cd development
          sed -i -e 's@state_rg@'$DEV_APP_RESOURCE_GROUP_NAME'@g' main.tf
          sed -i -e 's@state_sa@'$DEV_STORAGE_ACCOUNT_NAME'@g' main.tf
          sed -i -e 's@state_cn@'$DEV_CONTAINER_NAME'@g' main.tf
          sed -i -e 's@state_ak@'${{needs.get-key.outputs.output-access-key}}'@g' main.tf
          terraform init
          terraform apply -auto-approve